// Team primary colors + logos, generated by scripts/build_data.py from nflverse.
import teamsJson from "../../data/teams.json";

export type TeamMeta = { name: string; color: string; color2: string; logo: string; conf: string; division: string };
export const TEAMS = teamsJson as unknown as Record<string, TeamMeta>;

export function teamColor(abbr: string): string {
  return TEAMS[abbr]?.color ?? "#0B691C";
}
export function teamColor2(abbr: string): string {
  return TEAMS[abbr]?.color2 ?? teamColor(abbr);
}
export function logoUrl(abbr: string): string {
  return TEAMS[abbr]?.logo ?? "";
}

// Perceived brightness, and a mix toward white to guarantee a color reads on a
// dark background.
function lum(hex: string): number {
  const n = parseInt(hex.slice(1), 16);
  return 0.299 * ((n >> 16) & 255) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255);
}
function lighten(hex: string, target: number): string {
  const n = parseInt(hex.slice(1), 16);
  let r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  for (let i = 0; i < 20 && lum(`#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`) < target; i++) {
    r = Math.round(r + (255 - r) * 0.12); g = Math.round(g + (255 - g) * 0.12); b = Math.round(b + (255 - b) * 0.12);
  }
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`;
}

/** Trend-line color for dark mode: the team's secondary color, but if it's too
 *  dark to read on the dark-green background, fall back to primary / lighten. */
export function teamColorDark(abbr: string): string {
  const c2 = teamColor2(abbr), c1 = teamColor(abbr);
  const pick = lum(c2) >= 70 ? c2 : lum(c1) >= 70 ? c1 : c2;
  return lum(pick) >= 70 ? pick : lighten(pick, 120);
}

// ── conditional-format scale ─────────────────────────────────────────────────
// green above the mean, purple below, anchored to theme tokens so it reads in
// both light and dark mode.
/** Font color for an Elo number: green above the mean, purple below. Center ~1500; span ±160. */
export function eloTextColor(elo: number): string {
  const t = Math.max(-1, Math.min(1, (elo - 1500) / 160));
  if (Math.abs(t) < 0.05) return "var(--color-text)";
  const intensity = Math.round((0.4 + 0.6 * Math.min(1, Math.abs(t))) * 100);
  const anchor = t > 0 ? "var(--heat-green)" : "var(--heat-purple)";
  return `color-mix(in srgb, ${anchor} ${intensity}%, var(--color-text))`;
}

/** Green fill for a probability cell (0..1). */
export function oddsHeat(x: number): { bg: string; fg: string } {
  const a = Math.max(0, Math.min(1, x));
  return {
    bg: `color-mix(in srgb, var(--heat-green) ${Math.round(a * 78)}%, transparent)`,
    fg: a > 0.5 ? "#fff" : "var(--color-text)",
  };
}
