// Team primary colors + logos, generated by scripts/build_data.py from nflverse.
import teamsJson from "../../data/teams.json";

export type TeamMeta = { name: string; color: string; logo: string; conf: string; division: string };
export const TEAMS = teamsJson as unknown as Record<string, TeamMeta>;

export function teamColor(abbr: string): string {
  return TEAMS[abbr]?.color ?? "#0B691C";
}
export function logoUrl(abbr: string): string {
  return TEAMS[abbr]?.logo ?? "";
}

// ── conditional-format scale ─────────────────────────────────────────────────
// green above the mean, purple below, anchored to theme tokens so it reads in
// both light and dark mode.
/** Font color for an Elo number: green above the mean, purple below. Center ~1500; span ±160. */
export function eloTextColor(elo: number): string {
  const t = Math.max(-1, Math.min(1, (elo - 1500) / 160));
  if (Math.abs(t) < 0.05) return "var(--color-text)";
  const intensity = Math.round((0.4 + 0.6 * Math.min(1, Math.abs(t))) * 100);
  const anchor = t > 0 ? "var(--heat-green)" : "var(--heat-purple)";
  return `color-mix(in srgb, ${anchor} ${intensity}%, var(--color-text))`;
}

/** Green fill for a probability cell (0..1). */
export function oddsHeat(x: number): { bg: string; fg: string } {
  const a = Math.max(0, Math.min(1, x));
  return {
    bg: `color-mix(in srgb, var(--heat-green) ${Math.round(a * 78)}%, transparent)`,
    fg: a > 0.5 ? "#fff" : "var(--color-text)",
  };
}
